const AmazonConfig = {
    API_GATEWAY_URL: "PLACEHOLDER_API_URL",
    COGNITO_USER_POOL_ID: "PLACEHOLDER_POOL_ID",
    COGNITO_CLIENT_ID: "PLACEHOLDER_CLIENT_ID",
    COGNITO_HOSTED_UI_DOMAIN: "PLACEHOLDER_UI_DOMAIN"
};